# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [68]:
# Step 0 imports

import requests
from bs4 import BeautifulSoup
import pandas as pd

In [69]:
# Step 1 URL
books_url = "https://books.toscrape.com/"

# Step 2 User Agent Header
headers = {"User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari 537.36"}

In [70]:
# Step 3a Make the Requests and save the Response
books_response = requests.get(books_url, headers=headers)

In [71]:
#  Step 3b Test status code (Good practice)
if books_response.status_code == 200:
    print("Ok")
else:
    print("Not ok")

Ok

In [72]:
# Step 4 Parse the Response
books_soup = BeautifulSoup(books_response.content, "html.parser")

In [74]:
# Data Step 2 - Look at each element. Inspect the code to find where Title, Price, Rating, Genre, Availability, Description
print(all_articles[0].prettify())

<article class="product_pod">
 <div class="image_container">
  <a href="catalogue/a-light-in-the-attic_1000/index.html">
   <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
  </a>
 </div>
 <p class="star-rating Three">
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
 </p>
 <h3>
  <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
   A Light in the ...
  </a>
 </h3>
 <div class="product_price">
  <p class="price_color">
   £51.77
  </p>
  <p class="instock availability">
   <i class="icon-ok">
   </i>
   In stock
  </p>
  <form>
   <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
    Add to basket
   </button>
  </form>
 </div>
</article>

In [73]:
# Data Step 1 - Look at the HTML and figure out what you are searching for. 
# Search by tag - all that have the article tag. There are 20 on a page.
all_articles = books_soup.find_all("article")
print(len(all_articles))

20

In [89]:
# Build a Dataframe that uses a loop to go through each of the 20 articles and scrape these categories, adding them to a list

all_books = []

for a in all_articles:
    title_tag = a.find("h3")
    title_link = title_tag.find("a")
    title = title_link["title"]
    
    price_tag = a.find("p", class_="price_color")
    price = price_tag.text.strip()
    price = float(price.replace("£", ""))
    rating_tag = a.find("p", class_="star-rating")
    rating_word = rating_tag["class"][1]
    
    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
        }

    rating = rating_map[rating_word]

    avail_tag = a.find("p", class_="instock availability")
    availability = avail_tag.text.strip()
    
    all_books.append({
        "title":title,
        "price": price, 
        "rating": rating, 
        "availability": availability})

books_df = pd.DataFrame(all_books)
books_df.head(10)

,title,price,rating,availability
0,A Light in the Attic,51.77,3,In stock
1,Tipping the Velvet,53.74,1,In stock
2,Soumission,50.10,1,In stock
3,Sharp Objects,47.82,4,In stock
4,Sapiens: A Brief History of Humankind,54.23,5,In stock
5,The Requiem Red,22.65,1,In stock
6,The Dirty Little Secrets of Getting Your Dream...,33.34,4,In stock
7,The Coming Woman: A Novel Based on the Life of...,17.93,3,In stock
8,The Boys in the Boat: Nine Americans and Their...,22.60,4,In stock
9,The Black Maria,52.15,1,In stock

In [114]:
def scrape_books(min_rating, max_price):

    all_books = []

    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    for a in all_articles:

        # title
        title_tag = a.find("h3")
        title_link = title_tag.find("a")
        title = title_link["title"]

        # price
        price_tag = a.find("p", class_="price_color")
        price = float(price_tag.text.strip().replace("£", ""))

        # rating
        rating_tag = a.find("p", class_="star-rating")
        rating_word = rating_tag["class"][1]
        rating = rating_map[rating_word]

        # availability
        avail_tag = a.find("p", class_="instock availability")
        availability = avail_tag.text.strip()

        # FILTER (inside loop!)
        if price <= max_price and rating >= min_rating:
            all_books.append({
                "title": title,
                "price": price,
                "rating": rating,
                "availability": availability
            })

    return pd.DataFrame(all_books)

scrape_books(4, 20)

         title  price  rating availability
0  Set Me Free  17.46       5     In stock

In [117]:
scrape_books(2, 15)

                                            title  price  rating availability
0  Starving Hearts (Triangular Trade Trilogy, #1)  13.99       2     In stock

In [75]:
# Data Step 3: Save the data
# Title: Find <h3>, then find <a> and then look in the title attribute
#title_tag = article.find("h3")
#title_link = title_tag.find("a")
#title = title_link["title"]
#print(title)

In [76]:
# Price: Find <p> tag with class= "price_color"
#price_tag = article.find("p", class_="price_color")
#price = price_tag.text.strip()

#price = float(price.replace("£", ""))
#print(price)

In [77]:
# Rating is stored in <p> tag, class="star-rating"
#rating_tag = article.find("p", class_="star-rating")
#print(rating_tag["class"])

# Separate just the number word value
#rating_word = rating_tag["class"][1]
#print(rating_word)

In [78]:
# Availability is stored in <p> tag, class="instock availability"
#avail_tag = article.find("p", class_="instock availability")
#avail_tag

# Take the text out the code and remove any white space
#availability = avail_tag.text.strip()
#availability